// This root layout wraps BOTH route groups: (frontend) and (payload).
// Payload's admin layout renders its own <html>/<body>, so this root layout
// must NOT render them, otherwise /admin ends up with nested <html> elements.
// Each group owns its own document shell: (frontend)/layout.tsx renders the
// public site's <html>/<body>; (payload) is auto-generated by Payload.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
